components:
  gmmlib:
    dest_dir: gmmlib
    type: git
    branch: gmmlib
    revision: intel-gmmlib-19.4.1
    repository: https://github.com/intel/gmmlib.git
  igc:
    dest_dir: igc
    type: git
    branch: igc
    revision: ee341708a3d95738e942b6d3c5cd25b1f4b430f1
    repository: https://github.com/intel/intelgraphicscompiler
  infra:
    branch: infra
    dest_dir: infra
    revision: 6de26ad10381b9387ff3d11ca7f3215d87271c80
    type: git
  internal:
    branch: master
    dest_dir: internal
    revision: 158a02aaab227965c884137bcc18f3eed8412a4a
    type: git
  kmdaf:
    branch: kmdaf
    dest_dir: kmdaf
    revision: 117d709602a49f4aae6e7965743cec61834a3c35
    type: git
  libva:
    dest_dir: libva
    type: git
    branch: libva
    revision: c9bb65b
    repository: https://github.com/intel/libva.git
  wdk:
    dest_dir: wdk
    type: git
    branch: wdk
    revision: 39ec79c0ca347796daa7b07fbb81dd1bf45ccad5-1355
converter: M-1363
version: '1'
