components:
  gmmlib:
    branch: gmmlib
    clean_on_sync: true
    dest_dir: gmmlib
    repository: https://github.com/intel/gmmlib.git
    revision: fe9106bcb69a1f4572ec706765696b2b359c66a3
    type: git
  gmock:
    branch: master
    clean_on_sync: true
    dest_dir: gmock
    repository: https://github.com/google/googlemock.git
    revision: c440c8fafc6f60301197720617ce64028e09c79d
    type: git
  gtest:
    branch: master
    clean_on_sync: true
    dest_dir: gtest
    repository: https://github.com/google/googletest.git
    revision: c99458533a9b4c743ed51537e25989ea55944908
    type: git
  igc:
    branch: igc
    clean_on_sync: true
    dest_dir: igc
    repository: https://github.com/intel/intelgraphicscompiler
    revision: 021ca3b882973ba32e1b1582a273841778625bc7
    type: git
  infra:
    branch: infra
    clean_on_sync: true
    dest_dir: infra
    revision: a2764f8ed30e734087f3078ca7b0a621d7071a8a
    type: git
  internal:
    branch: master
    dest_dir: internal
    revision: 2f5771ae1b1110c5b9df6afa56121489e105706c
    type: git
  khronos:
    branch: master
    clean_on_sync: true
    dest_dir: khronos
    repository: https://github.com/KhronosGroup/OpenCL-Headers.git
    revision: f039db6764d52388658ef15c30b2237bbda49803
    type: git
  libdrm:
    branch: libdrm-2.4.84
    clean_on_sync: true
    dest_dir: libdrm
    repository: https://anongit.freedesktop.org/git/mesa/drm.git
    revision: 290d29d9794813a2fe0578dbb905ad09bc810516
    type: git
  wdk:
    branch: wdk
    clean_on_sync: true
    dest_dir: wdk
    revision: ad7ff91bc486b6369d55387fe0a42352a6a88bf3
    type: git
version: '1'
