components:
  gmmlib:
    dest_dir: gmmlib
    type: git
    branch: gmmlib
    revision: intel-gmmlib-19.4.1
    repository: https://github.com/intel/gmmlib.git
  igc:
    dest_dir: igc
    type: git
    branch: igc
    revision: 354256e38029e56fc8aa3b2034ee69d6cb181e32
    repository: https://github.com/intel/intelgraphicscompiler
  infra:
    branch: infra
    dest_dir: infra
    revision: 9833fb75b390eff66249f77ed2d67edc95e076f2
    type: git
  internal:
    branch: master
    dest_dir: internal
    revision: ee4326c570c0eee18d2a716a9e69f59700e5cfdb
    type: git
  kmdaf:
    branch: kmdaf
    dest_dir: kmdaf
    revision: 710b620b08792ba0367bcabd54c479ede7518603
    type: git
  libva:
    dest_dir: libva
    type: git
    branch: libva
    revision: c9bb65b
    repository: https://github.com/intel/libva.git
  wdk:
    dest_dir: wdk
    type: git
    branch: wdk
    revision: 39ec79c0ca347796daa7b07fbb81dd1bf45ccad5-1355
converter: M-1368
version: '1'
