components:
  gmmlib:
    branch: gmmlib
    clean_on_sync: true
    dest_dir: gmmlib
    repository: https://github.com/intel/gmmlib.git
    revision: 5cd8dca50b1f6ddbce229098dc2bec55fc922fa7
    type: git
  igc:
    branch: igc
    clean_on_sync: true
    dest_dir: igc
    repository: https://github.com/intel/intelgraphicscompiler
    revision: 67351f4e52f52eb2e4d68a9a40599a77733b5603
    type: git
  infra:
    branch: infra
    clean_on_sync: true
    dest_dir: infra
    revision: 6e020e45c91852cf77b3a9c9d7eeaaae6be42cd8
    type: git
  internal:
    branch: master
    dest_dir: internal
    revision: 90de55f1fcda63fa2eb7d404be7a4a44abdbd002
    type: git
  kmdaf:
    branch: kmdaf
    clean_on_sync: true
    dest_dir: kmdaf
    revision: 04aeec48c6eb777d675e5342541b5c3fc2997280
    type: git
  libva:
    branch: libva
    clean_on_sync: true
    dest_dir: libva
    repository: https://github.com/intel/libva.git
    revision: c9bb65b
    type: git
  wdk:
    branch: wdk
    clean_on_sync: true
    dest_dir: wdk
    revision: 4423584cd5bfda14bb324142159b5affb5461d26-1165
    type: git
converter: M-1174
version: '1'
