components:
  gmmlib:
    clean_on_sync: true
    dest_dir: gmmlib
    type: git
    branch: gmmlib
    revision: intel-gmmlib-19.3.4
    repository: https://github.com/intel/gmmlib.git
  igc:
    clean_on_sync: true
    dest_dir: igc
    type: git
    branch: igc
    revision: 796782e33f9dd5bd6836dda59e54a7a9e53c4203
    repository: https://github.com/intel/intelgraphicscompiler
  infra:
    branch: infra
    clean_on_sync: true
    dest_dir: infra
    revision: c571d76ddddd9d962504aa6f30a62b0b2d76a88b
    type: git
  internal:
    branch: master
    dest_dir: internal
    revision: 17dadee01d2b1446cf2323f62d75d0178d79b600
    type: git
  kmdaf:
    branch: kmdaf
    clean_on_sync: true
    dest_dir: kmdaf
    revision: 117d709602a49f4aae6e7965743cec61834a3c35
    type: git
  libva:
    clean_on_sync: true
    dest_dir: libva
    type: git
    branch: libva
    revision: c9bb65b
    repository: https://github.com/intel/libva.git
  wdk:
    clean_on_sync: true
    dest_dir: wdk
    type: git
    branch: wdk
    revision: 682c4e3d433c6796acebfcbc8f0e2a5135f58412-1330
converter: M-1335
version: '1'
