components:
  gmmlib:
    branch: gmmlib
    clean_on_sync: true
    dest_dir: gmmlib
    repository: https://github.com/intel/gmmlib.git
    revision: 941eda5eb4668da0f4511fcab77c4660b7097d5d
    type: git
  igc:
    branch: igc
    clean_on_sync: true
    dest_dir: igc
    repository: https://github.com/intel/intelgraphicscompiler
    revision: d1dff9b32507679d6bdf07c0104741f83dfb80bb
    type: git
  infra:
    branch: infra
    clean_on_sync: true
    dest_dir: infra
    revision: 04e8c36c3f011a72f230c843b97f7ff2d15c7124
    type: git
  internal:
    branch: master
    dest_dir: internal
    revision: 7a3e9e74879064dc3b68bb7bd684adc388e4b841
    type: git
  kmdaf:
    branch: kmdaf
    clean_on_sync: true
    dest_dir: kmdaf
    revision: 99402337f2b42a058a1b20cb0dc130033fdbd65f
    type: git
  wdk:
    branch: wdk
    clean_on_sync: true
    dest_dir: wdk
    revision: 790647-1082
    type: git
converter: M-1082
version: '1'
