components:
  gmmlib:
    branch: gmmlib
    clean_on_sync: true
    dest_dir: gmmlib
    repository: https://github.com/intel/gmmlib.git
    revision: intel-gmmlib-19.2.3
    type: git
  igc:
    branch: igc
    clean_on_sync: true
    dest_dir: igc
    repository: https://github.com/intel/intelgraphicscompiler
    revision: 8ded4d572177e46139cf29febcbd1e48dd89b235
    type: git
  infra:
    branch: infra
    clean_on_sync: true
    dest_dir: infra
    revision: e597fa79a152abae1b3637000c70f867994146e9
    type: git
  internal:
    branch: master
    dest_dir: internal
    revision: 49509387fe2557082b9d606e5a77deb9495af061
    type: git
  kmdaf:
    branch: kmdaf
    clean_on_sync: true
    dest_dir: kmdaf
    revision: a56f5ee43b873b74377d387e25d64cfebde5795d
    type: git
  libva:
    branch: libva
    clean_on_sync: true
    dest_dir: libva
    repository: https://github.com/intel/libva.git
    revision: c9bb65b
    type: git
  wdk:
    branch: wdk
    clean_on_sync: true
    dest_dir: wdk
    revision: a4ef754827742dffa3fbf749545909878d65f0a1-1267
    type: git
converter: M-1268
version: '1'
