components:
  gmmlib:
    branch: gmmlib
    clean_on_sync: true
    dest_dir: gmmlib
    repository: https://github.com/intel/gmmlib.git
    revision: 3e602a84dccda56200bfb7846066ece6259841c9
    type: git
  igc:
    branch: igc
    clean_on_sync: true
    dest_dir: igc
    repository: https://github.com/intel/intelgraphicscompiler
    revision: de3d1de3456cf5b6f312bdafb8709538f19cb854
    type: git
  infra:
    branch: infra
    clean_on_sync: true
    dest_dir: infra
    revision: e37491fe017783a08cac088c7e07920fd203456b
    type: git
  internal:
    branch: master
    dest_dir: internal
    revision: 170916ffe6a2acaed65aa2b59c5c1b9993037c21
    type: git
  kmdaf:
    branch: kmdaf
    clean_on_sync: true
    dest_dir: kmdaf
    revision: 70be2c96ab6a6ddbd8987b89f8818a6a0858ffdd
    type: git
  wdk:
    branch: wdk
    clean_on_sync: true
    dest_dir: wdk
    revision: 790647-1082
    type: git
converter: M-1097
version: '1'
